"""Python port of ``agents/src/tools/git-tools.ts`` (uses GitPython + gh CLI)."""

from __future__ import annotations

import asyncio
import re
import subprocess

from git import GitCommandError, Repo

from config import CONFIG


def _get_repo() -> Repo:
    return Repo(str(CONFIG.project_root))


async def create_branch(task_id: str, title: str) -> str:
    def _create() -> str:
        repo = _get_repo()
        slug = re.sub(r"[^a-z0-9]+", "-", title.lower())
        slug = re.sub(r"(^-|-$)", "", slug)[:40]
        branch_name = f"agent/{task_id}-{slug}"

        current_branch = repo.active_branch.name
        print(f"  Current branch: {current_branch}")

        repo.git.checkout("-b", branch_name)
        print(f"  \u2713 Created and switched to branch: {branch_name}")
        return branch_name

    return await asyncio.to_thread(_create)


async def commit_step(step_number: int, title: str, files_changed: list[str]) -> None:
    def _commit() -> None:
        repo = _get_repo()

        if not files_changed:
            print(f"  No files to commit for step {step_number}")
            return

        for file in files_changed:
            try:
                repo.git.add(file)
            except GitCommandError:
                repo.git.add(".")
                break

        message = f"agent: step {step_number} - {title}"
        repo.git.commit("-m", message)
        print(f"  \u2713 Committed: {message}")

    await asyncio.to_thread(_commit)


async def push_branch(branch_name: str) -> None:
    def _push() -> None:
        repo = _get_repo()
        try:
            repo.git.push("origin", branch_name, "--set-upstream")
            print(f"  \u2713 Pushed branch: {branch_name}")
        except GitCommandError as error:
            print(f"  \u26a0 Could not push (no remote?): {error}")

    await asyncio.to_thread(_push)


async def create_pull_request(
    branch_name: str,
    task_title: str,
    plan_summary: str,
    steps_completed: int,
) -> str | None:
    try:
        await push_branch(branch_name)
    except Exception:
        print("  \u26a0 Skipping PR creation \u2014 could not push")
        return None

    title = f"[Agent] {task_title}"
    body = (
        f"## Summary\n\n{plan_summary}\n\n"
        f"## Steps Completed\n\n{steps_completed} steps implemented by the dev agent.\n\n"
        "## Review\n\nThis PR was generated by the Joyalty Dev Agent. Please review carefully."
    )

    def _create_pr() -> str | None:
        try:
            proc = subprocess.run(
                [
                    "gh", "pr", "create",
                    "--title", title,
                    "--body", body,
                    "--head", branch_name,
                ],
                cwd=str(CONFIG.project_root),
                capture_output=True,
                text=True,
                check=True,
            )
            pr_url = proc.stdout.strip()
            print(f"  \u2713 Created PR: {pr_url}")
            return pr_url
        except (subprocess.CalledProcessError, FileNotFoundError) as error:
            detail = getattr(error, "stderr", None) or str(error)
            print(f"  \u26a0 Could not create PR (gh CLI not configured?): {detail}")
            return None

    return await asyncio.to_thread(_create_pr)


async def get_current_branch() -> str:
    def _current() -> str:
        return _get_repo().active_branch.name

    return await asyncio.to_thread(_current)


async def switch_branch(branch_name: str) -> None:
    def _switch() -> None:
        _get_repo().git.checkout(branch_name)

    await asyncio.to_thread(_switch)


async def has_uncommitted_changes() -> bool:
    def _check() -> bool:
        return _get_repo().is_dirty(untracked_files=True)

    return await asyncio.to_thread(_check)


async def get_step_diff(
    files_changed: list[str],
    committed: bool,
    max_chars: int = 6_000,
) -> str:
    """Return a human-readable diff for the changes a step just made.

    When ``committed`` is true the work was committed (branch mode), so we show
    the most recent commit. Otherwise we show the working-tree diff for the
    touched files (uncommitted mode). The result is capped so a large diff can't
    flood the review prompt.
    """

    def _diff() -> str:
        repo = _get_repo()
        try:
            if committed:
                text = repo.git.show("HEAD", "--stat", "-p")
            elif files_changed:
                text = repo.git.diff("--", *files_changed)
            else:
                text = repo.git.diff()
        except GitCommandError as error:
            return f"(could not compute diff: {error})"
        text = text or "(no textual diff — likely new/binary files only)"
        if len(text) > max_chars:
            text = text[:max_chars] + "\n... (diff truncated)"
        return text

    return await asyncio.to_thread(_diff)
